
language: node_js

node_js: '10'

os:
  - linux
  - osx

before_install:
  - npm install -g npm@6.4.0

install:
  - npm install

script:
  - cat package-lock.json
  - git diff package-lock.json --exit-code
